name: Publish Docker image

on:
  push:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # To log into a third party registry, set the registry key below.

          # This is the GitHub Container Registry
          #registry: ghcr.io

          # This is GitLab
          #registry: registry.gitlab.com

          # This is the Azure Container Registry
          #registry: <registry-name>.azurecr.io

          # This is the Google Container Registry
          #registry: gcr.io

          # These credentials assume existing secrets for DockerHub
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          #tags: user/app:latest
